title: Adams Blog
author: "Adam Vincze"
description: Personal Blog

minima:
  date_format: "%Y-%m-%d"

twitter_username: advincze
github_username:  advincze
rss: rss
  

google_analytics: "UA-61034122-1"

header_pages:
- about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag