title: Adams Blog
author:
  name: "Adam Vincze"
  email: your-email@domain.com
description: Personal Blog

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"
  # generate social links in footer
  social_links:
    twitter: "advincze"
    github:  "advincze"
    # linkedin: jekyll
    # keybase: jekyll

google_analytics: "UA-61034122-1"

header_pages:
- about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag