baseurl : https://advincze.github.io/
languageCode : "en-us"
title: "adams code foo"
author: "advincze"
theme: "pixyll" # ok, simple
relativeURLs: true
publishDir: docs
enableRobotsTXT: true

indexes:
  tag: tags
params:
  google_analytics_id: "UA-61034122-1"
  twitter_username: "advincze"
  disqus_shortname: "advincze"
  # paginate: false